config/routes.rb
Rails.application.routes.draw do

 root "pics#index"
 devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :pics do
  	resource :like, module: :pics
  	resources :comments
  end


  # get '/pic/likes', to: 'pics#update_like'
  get '/about', to: 'pages#about'
  #get '/mail', to: 'pages#mail'

  # get '/auth/:provider/callback', to: 'sessions#create'

  # get 'auth/:provider/callback', to: 'sessions#create'


end

app/views/shared/_footer.html.haml
.footer
  .social-icons.pull-right
    = link_to image_tag( 'http://www.womenactionmedia.org/cms/assets/themes/crate/images/social/facebook.png'), 'https://www.facebook.com/sampurna.chapagain'
    / .social
    /   = button_tag "<i id='github', class='icon-github'></i>".html_safe

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse
  .container
    %ul.nav.navbar-right
      -Category.all.each do |category|
        %li= link_to category.name, pics_path(category: category.name)
    .container
      .navbar-brand= link_to "Instagram", root_path
      =#link_to "Sign in with twitter", "/auth/twitter"
      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-left
          %li= link_to "Gram It!", new_pic_path
          %li= link_to "Settings", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete

      -else
        %ul.nav.navbar-left
          %li= link_to "Join", new_user_registration_path
          %li= link_to  "Log In", new_user_session_path
          %li= link_to "Sign in using facebook", user_facebook_omniauth_authorize_path
          %li= link_to "Sign in with Twitter", user_twitter_omniauth_authorize_path