config/routes.rb
Rails.application.routes.draw do

 root "pics#index"
 devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :pics do
  	resource :like, module: :pics
  	resources :comments
  end


  # get '/pic/likes', to: 'pics#update_like'
  get '/about', to: 'pages#about'
  #get '/mail', to: 'pages#mail'

  # get '/auth/:provider/callback', to: 'sessions#create'

  # get 'auth/:provider/callback', to: 'sessions#create'


end

app/models/pic.rb
class Pic < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	mount_uploader :avatar, AvatarUploader
	has_many :likes
	belongs_to :category

	def self.search(search)
		# where("title LIKE ?", "%#{search}%")
		where(title: search)
	end
end

app/controllers/pics/likes_controller.rb
class Pics::LikesController < ApplicationController 
	before_action :authenticate_user!
	before_action :set_post

	
	def create
		@pic.likes.where(user_id: current_user.id).first_or_create
		respond_to do |format|
			format.html { redirect_to @pic }
			format.js
		end
	end
  

  def destroy
  	@pic.likes.where(user_id: current_user.id).destroy_all
  	respond_to do |format|
			format.html { redirect_to @pic }
			format.js
		end
  end

	private

	  def set_post
		@pic = Pic.find(params[:pic_id])
		end
  
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

  before_action :find_pics, only: [:show, :edit, :update, :destroy]

  def index

    if params[:search]
      @pics = Pic.search(params[:search]).page(params[:page]).per(3)
    else
      if params[:category].blank?
        @pics = Pic.all.order('created_at DESC').page(params[:page]).per(3)
      else
        @category_id = Category.find_by(name: params[:category]).id
        @pics = Pic.where(category_id: @category_id).order("created_at DESC").page(params[:page]).per(3)
      end
    end
  end

  def show
  end

  def new
    @pic = current_user.pics.build
  end

  def create
    @pic = current_user.pics.build(pic_params)
    if @pic.save
      redirect_to @pic, notice: "Yes, it was posted !"
    else
      render 'new'
    end
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: "Congrats! Pic was updated !"
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to pics_path
  end

  # def update_like
  #   user = params["user_id"].to_i
  #   pic = Pic.find params["pic_id"].to_i

  #   pic.like += 1
  #   pic.save

  #   respond_to do |format|
  #     format.json { render :json => { like_count: pic.like } }
  #   end
  # end


  private

  def pic_params
    params.require(:pic).permit(:title, :description, :avatar, :category_id)
  end

  def find_pics
    @pic = Pic.find(params[:id])
  end

end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true } do |f|
  - if @pic.errors.any?
    %h2 = pluralize(@pic.errors.count, "error") prevented this pic from saving !
    %ul
      -@pic.errors.full_messages.each do |msg|
        %li= msg
  .form-group
    = f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category" }, class: "form-control"
    = f.input :title, input_html:{ class: 'form-control' }
  .form-group
    = f.input :description, input_html:{ class: 'form-control' }
    = f.file_field :avatar, input_html:{ class: 'form-control' }

  =# render 'form', locals: { f: f }
  = f.button :submit, class: "btn btn-info"

= link_to "Back", root_path

app/views/pics/_like.html.haml
-if user_signed_in? && current_user.likes?(@pic)
	= link_to "Unlike", pic_like_path(@pic), method: :delete, class: "glyphicon glyphicon-heart-empty like-unsuccess"
-else
	= link_to "Like", pic_like_path(@pic), method: :post, class: "glyphicon glyphicon-heart-empty like-success"

.badge.badge-notify
	=#@pic.likes.count if @pic.try(:likes)
	=@pic.try(:likes).try(:count)

app/views/pics/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Post Pic
			.panel-body
				.current_image
					%strong.center Right Now
					= image_tag @pic.avatar.url,class: "img-responsive"
				=render 'form'

app/views/pics/index.html.haml
.col-md-12
  .col-md-4.col-xs-4.col-sm-4
  .col-md-4.col-xs-4.col-sm-4
    #pics.transitions-enabled
      =form_tag pics_path, :method => 'get' do
        .input-group
          =text_field_tag :search
          = button_tag "<i class='fa fa-search'></i>".html_safe, class: 'btn btn-primary'

        - @pics.each do |pic|
          .box.panel.panel-default
            %h2= link_to pic.title, pic
            = link_to (image_tag pic.avatar.url), pic
        = paginate @pics,:theme => 'twitter-bootstrap-3'
  .col-md-4.col-xs-4.col-sm-4

app/views/pics/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Post Pic
			.panel-body
				=render 'form'

app/views/pics/show.html.haml
= javascript_include_tag 'like.js'

#pic_show.row
	.col-md-6.col-md-offset-3
		.panel.panel-default
			= image_tag @pic.avatar.url, class: 'img-responsive'
		.panel-body
			%h1= @pic.title
			%p= @pic.description

		.panel-footer
			.row
				.col-md-6
					%p.user
						by
						= @pic.user.email
						| Submitted at :
						=time_ago_in_words(@pic.created_at)
						ago
						.hidden#pic-id
							= @pic.id
						.hidden#user-id
							= @pic.user.id
				.col-md-6
					.btn-group.pull-right
						-	if (user_signed_in? && current_user.pics.pluck(:id).include?(@pic.id))
							=link_to "Edit", edit_pic_path, class: "btn btn-info"
							=link_to "Delete", pic_path(@pic), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
						#likes
						=render partial: "like", locals: {pic: @pic}

			#comments
			=render @pic.comments
			=render partial: "comments/form"